<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	///\vendor\yongtiger\yii2-category\src\models\Category.php
	'ID' => 'ID',
	'Name' => '名称',

	///\vendor\yongtiger\yii2-category\src\views\default\index.php
	'Categories' => '目录',
	'Are you sure you want to delete this item and its children?' => '您确定要删除此项及全部子项吗？',

	///\vendor\yongtiger\yii2-category\src\views\manage\_form.php
	'Save' => '保存',

	///\vendor\yongtiger\yii2-category\src\views\manage\_search.php
	'Search' => '保存',
	'Reset' => '保存',

	///\vendor\yongtiger\yii2-category\src\views\manage\view.php
	'Are you sure you want to delete this item?' => '您确定要删除此项吗？',
	'Update' => '更新',
	'Delete' => '删除',

	///\vendor\yongtiger\yii2-category\src\views\manage\update.php
	'Update Category: ' => '更新目录：',

	///\vendor\yongtiger\yii2-category\src\views\manage\index.php
	'Create Category' => '创建目录',
];
